gitlab:
  url: "http://git.example.com" # gitlab地址
  token: "yourGitLabToken" # gitlab token
oss:
  accessKeyId: "yourAliyunAccessKeyId" # oss accessKeyId
  accessSecret: "yourAliyunAccessKeyIdSecret" # oss accessSecret
  bucketName: "yourBackupBucketName" # 备份存储的 oss bucketName
  endpoint: "oss-cn-beijing.aliyuncs.com"
keepLocalBackup: false # 是否保留本地备份
